### ISSUE TITLE
Can't unarchive release zip

### ISSUE THREAD

**Issue by jmas** [korzhyk/OSX-Ukrainian-Unicode-Layout#13]
<img width="397" alt="Знімок екрана 2022-03-16 о 14 27 16" src="https://user-images.githubusercontent.com/90701/158589788-2d0e59ce-918b-430b-934e-3795fc7c2781.png">

<img width="603" alt="Знімок екрана 2022-03-16 о 14 28 04" src="https://user-images.githubusercontent.com/90701/158589937-f11f5e1e-429c-4466-9d7b-db5135603eda.png">

**Comment by korzhyk** [comment]
@jmas перевір, будь ласка, чи файл не пошкоджений

```bash
➜ shasum Install.Ukrainian.Unicode.Layout.app.zip 
9a3d8d3594cdfc5d959b1cdc990be7eb40498ce2  Install.Ukrainian.Unicode.Layout.app.zip
```

**Comment by jmas** [comment]
@korzhyk Завантажив ще раз, перевірив, хеш збігається.

```
$ shasum Install.Ukrainian.Unicode.Layout.app.zip
9a3d8d3594cdfc5d959b1cdc990be7eb40498ce2  Install.Ukrainian.Unicode.Layout.app.zip
$ date
чт 17 бер 2022 18:59:06 EET
```

**Comment by korzhyk** [comment]
@jmas спробуй інші два варіанти через brew або git

**Comment by jmas** [comment]
@korzhyk Дякую, через brew працює!
