### ISSUE TITLE
Macbook OS X Monterey Slack завжди автоматично переключає мову на англійську(

### ISSUE THREAD

**Issue by Hannibal2** [korzhyk/OSX-Ukrainian-Unicode-Layout#14]
Macbook OS X Monterey Slack завжди автоматично переключає мову на англійську(.
Спробував змінити мову самого Slack – не допомогло (як через налаштування самого slack так і через налаштування мові та регіону через налаштування Mac, думав якщо поставити російську, але не допомогло).
Також спробував в налаштуваннях клавіатури вкл/викл опцію Automatically switch to a document's input source — також не допомогло. 
Можливо хтось стикався і знайшов якесь рішення?

**Comment by Hannibal2** [comment]
на сайті Slack знайшов 
https://slack.com/help/articles/115005429666-Manage-your-keyboard-layout#select-your-keyboard-layout

**Comment by dstorozhuk** [comment]
> на сайті Slack знайшов https://slack.com/help/articles/115005429666-Manage-your-keyboard-layout#select-your-keyboard-layout

Не працює. Просто не мае дропдауну с вибором Keyboard layout. 

<img width="799" alt="Slack | Maria Chernenko | iTech4Web 2022-03-21 17-47-57" src="https://user-images.githubusercontent.com/2509744/159298606-d5c4099d-0bae-4fbc-869b-fa38dc79fed3.png">

**Comment by dstorozhuk** [comment]
Ага. Я разобрался. Нужно выбрать не Ukranian unicode а именно Ukranian

![Monosnap 2022-03-21 18-16-23](https://user-images.githubusercontent.com/2509744/159304312-cac8c795-7398-449e-a63b-3fc18e29f19d.png)

**Comment by Hannibal2** [comment]
> Ага. Я разобрался. Нужно выбрать не Ukranian unicode а именно Ukranian
> 
> ![Monosnap 2022-03-21 18-16-23](https://user-images.githubusercontent.com/2509744/159304312-cac8c795-7398-449e-a63b-3fc18e29f19d.png)

Працює!
