### ISSUE TITLE
Якщо після інсталювання глючить

### ISSUE THREAD

**Issue by Nikaaner** [korzhyk/OSX-Ukrainian-Unicode-Layout#3]
Інсталював розкладку в High Sierra 10.13.1 для одного користувача (як було вказано, в ~/Library), але [глюки](https://apple.stackexchange.com/questions/300606/keyboard-layout-keeps-reverting-since-upgrade-to-high-sierra) всеодно були присутні, з якими користуватися розкладкою неможливо.

1. Видалив з ~/Library/Keyboard Layouts, але в налаштуваннях системи в джерелах вводу в списку з якого можна вибирати потрібні розкладки ця розкладка не зникла навіть після перезавантаження. 
2. Перевірив /System/Library/Keyboard Layouts,  /Library/Keyboard Layouts, та ~/Library/Keyboard Layouts, але ніде її немає. Значить проблема з кешем.
3. [Перезавантажився у Safe Mode](https://support.apple.com/kb/PH25617?locale=en_US&viewlocale=en_US), таким чином кеші почистилися, і в налаштуваннях в джерелах вводу розкладка зникла.

Заново інсталював для одного користувача і все запрацювало без глюків.

Підозрюю що проблема виникла через те що колись у мене вже була встановлена розкладка Ukrainian Unicode, хоч потім і була видалена, кеші її всеодно пам'ятали.

**Comment by tsdaemon** [comment]
А які саме глюки? В мене все ок, але в Слаку не працює, друкує англійською.

**Comment by Nikaaner** [comment]
Там прикріплене посилання до слова «глюки» для того щоб було зрозуміло що саме я мав на увазі. Ось воно https://apple.stackexchange.com/questions/300606/keyboard-layout-keeps-reverting-since-upgrade-to-high-sierra <https://apple.stackexchange.com/questions/300606/keyboard-layout-keeps-reverting-since-upgrade-to-high-sierra>

**Comment by nashbridges** [comment]
Перестрибнув зі Sierra на Monterey.

Спробував спочатку встановити для поточного користувача в ~/Library/Keyboard\ Layouts, як вказано в Readme. 
Запрацювало частково: якщо знаходишся в iTerm або налаштуваннях системи, то розкладка перемикається (як з клавіатури, так і курсором через список вгорі), якщо знаходишся в Safari, то не перемикається взагалі.

Видалив з поточного користувача і встановив глобально в /Library/Keyboard\ Layouts – аналогічний результат.
Заувага: Readme рекомендує встановлювати в /System/Library/Keyboard\ Layouts, але вона захищена SIP.

І лише заґуґливши схожий випадок, скопіював розкладку в обидва місця, тепер перемикається всюди.

Ось схожий випадок для розуміння — [Custom keyboard layout not selectable for most programs](https://discussions.apple.com/thread/250820750):

> I copied my custom keyboard layout from the old Macbook to the new one into the folder ~/Library/Keyboard Layouts .
> 
> I went into System Preferences / Keyboard / Input sources; I added it using the "+" sign, and it now appears alright in the left bar. It also appears in the Input menu at the top right , together with the original layout (US) and Emoji viewer, etc.
> 
> However, when I am trying to select this keyboard layout, it does not work.
> 
> What is funny is that it works only when one of a very few programs is the front program, such as Terminal, GVim, or System Preferences.
> 
> Needless to say that it worked perfectly on my old Macbook just a week ago.
> Both laptops run under Mojave 10.14.6.
>

**Comment by stridor5** [comment]
Добрий день. Встановив на ейрі 2020 (м1, Монтерей) розкладку, поклав у папки локальну та глобальу keyborard layouts, але серед доступних розкладок не зʼявився Ukrainian Unicode - лише просто Ukrainian. На цій розкладці також перемикається і/ы, як на юнікоді, але, наприклад на кноці ~ знаходиться буква ґ, а на кнопці ] - ї, а апостороф на кнопці \|.
Моє питання: це юнікод на новому маку поміняв розкладку, чи це все-таки не та розкладка і юнікод не встановився? Якщо друге, то як його правильно встановити? Бо пробував і через інсталятор, і вручну на обох юзерів - все марно.

<img width="528" alt="Screenshot 2022-12-05 at 12 35 10" src="https://user-images.githubusercontent.com/119854797/205616348-92cdd5b8-7f05-4a67-8757-798f179f59df.png">

**Comment by andriy-appuchino** [comment]
Привіт. То юнікод не встановився. У мене ейр 2022 (м2, Вентура). Мені здається що і через інсталятор і через brew встановлювалося успішно, тільки з невеликим багом.

**Comment by Nikaaner** [comment]
Привіт. То юнікод не встановився. У мене ейр 2022 (м2, Вентура). Мені здається що і через інсталятор і через brew встановлювалося успішно, тільки з невеликим багом.

**Comment by stridor5** [comment]
дякую. а якої інструкції краще дотримуватися? бо я не дуже досвідчений макюзер, не шарю оце брю і все таке

**Comment by Nikaaner** [comment]
Та воно без різниці, просто різні варіанти встановлення. Я спробував обидва бо думав що може в іншому варіанті багу не буде. [У мене в налаштуваннях відображається 2 юнікод розкладки але працює тільки одна з них.](https://github.com/korzhyk/OSX-Ukrainian-Unicode-Layout/issues/15#issuecomment-1207302151)
