### ISSUE TITLE
"Забування" розкладки в High Sierra

### ISSUE THREAD

**Issue by sasha817** [korzhyk/OSX-Ukrainian-Unicode-Layout#4]
Вітаю,
Щойно знайшов спосіб підсунути розкладку High Sierra так, аби вона не забувала про існування розкладки після перезавантаження: властиво, розкладку треба разом з іконкою впакувати в окремий bundle, скопіювавши який в /Library/Keyboard Layouts все стає на свої місця.
Зробити pull request чи Ви додасте самі коли буде час/бажання?

**Comment by korzhyk** [comment]
Буду вдячний за pull-request. Тому, що я поки не планую переходити на HS щоб зміг поправити розкладу. Дякую!

**Comment by Nikaaner** [comment]
@sasha817 У мене на High Sierra були проблеми з переключенням на цю розкладку, коли вона була в /Library/Keyboard Layouts, тому я переніс в ~/Library/Keyboard Layouts. Точно проблем не буде?

**Comment by sasha817** [comment]
@korzhyk я ввечері зроблю, позаяк воно на домашньому комп’ютері живе.

@Nikaaner бачите, коли я просто клав в глобальну папочку .keylayout та .icns, система просто про них "забувала" після перезавантаження - далі я не експериментував. В користувацькій `~/Library/Keyboard Layouts` все працювало. І лише перепакування тих файликів у bundle в Ukelele вирішило проблему: після перезавантаження не зникає, переключається стабільно, доступно для всіх користувачів. 

Мабуть, стикнувся з цим, бо в наявності пара макбуків з парою користувачів кожен (склалося історично), а робити всім і кожному окремо і ще на робочому маку мені банально ліньки. Та й "фікс" знайшовся доволі випадково.
