### ISSUE TITLE
Потрібно навести лад в репо

### ISSUE THREAD

**Issue by korzhyk** [korzhyk/OSX-Ukrainian-Unicode-Layout#6]
- [ ] Адаптувати для High Sierra
- [x] Прибрати інсталятор

- [x] Можливо переробити README

**Comment by Tusko** [comment]
то як там з Sierra?
бо в мене щоразу таке, коли запускаю компа 
http://cl.ly/p35r
http://cl.ly/p2x3

**Comment by marchenko1985** [comment]
А де я можу побачити ісходні коди додатку? Якщо розумію вірно то тут вже скомпільований додаток котрий міг би жити в releases

**Comment by Tusko** [comment]
@mac2000 
https://github.com/korzhyk/OSX-Ukrainian-Unicode-Layout/tree/master/Install%20Ukrainian%20Unicode%20Layout.app/Contents

**Comment by marchenko1985** [comment]
Дійсно, дійшов до `Ukrainian Unicode.keylayout`, але все ще не зрозуміло як можна склонувати репо, запровадити зміни, скомпілювати - мав на увазі саме це

**Comment by korzhyk** [comment]
Ну, що ж. Сьогодні трішки привів до ладу репозиторій. Тепер сама розкладка знаходиться у іншому проекті https://github.com/korzhyk/macOS-Ukrainian-Unicode-Layout
