### ISSUE TITLE
Ukrainian - PC розкладка із "\"  та "/" замість "ґ" and "Ґ"

### ISSUE THREAD

**Issue by kalbason** [korzhyk/OSX-Ukrainian-Unicode-Layout#7]
У разі спроби виправити настандартне розміщенням крапки та коми в дефолтних розкладках МакОС для української мови, постає проблема повної відсутності слешів в українській розкладці, якщо просто кому та крапку перенести на місце клавіші "/?". 
Для вирішення цієї проблеми пропоную піти тим самим шляхом, як це зроблено у вбудованій "Russian - PC" розкладці (вони прибрали літеру що рідко використовується - "Ё"). Такою ж літерою в українській мові є "Ґ". Тобто, на місце "ґ" та"Ґ" ставимо " \ "  та " / ". 
І отримуємо Ukrainian (Enhanced) Keyboard Layout з windows.

Рокладка тоді виглядає наступним чином:
1) стандартний режим
<img width="667" alt="01-normal" src="https://user-images.githubusercontent.com/40061576/41158143-9565a192-6b30-11e8-94d4-2d55ae41bad9.png">

2) режим з натиснутим shift
<img width="666" alt="02-shift" src="https://user-images.githubusercontent.com/40061576/41179423-566e9780-6b73-11e8-8134-abea53f65a52.png">

Для інсталяції потрібно розпакувати zip архів, скопіювати Ukrainian - PC.bundle файл в "~/Library/Keyboard Layouts" дирекеторію, запустити System Preferences -> Keyboard ->Input sources та вибрати модифіковану "Ukrainian - PC" розкладку.

<img width="671" alt="install" src="https://user-images.githubusercontent.com/40061576/41158287-0aeccfb2-6b31-11e8-945c-8c2cfd602cd6.png">

Ось сама розкладка:
[Ukrainian - PC.bundle.zip](https://github.com/korzhyk/OSX-Ukrainian-Unicode-Layout/files/2085947/Ukrainian.-.PC.bundle.zip)

Літeра ґ набираєтся через Option+г (Option+u)

**Comment by Nikaaner** [comment]
Не збивайте людей з толку. В Ukrainian Unicode є всі слеші, достатньо затиснути клавішу Option.
Деталі на [https://r2u.org.ua/wiki/keyboard/UkrainianUnicode](url)
