### ISSUE TITLE
Ukrainian Unicode відображається двічі

### ISSUE THREAD

**Issue by valsoray17** [korzhyk/OSX-Ukrainian-Unicode-Layout#8]
Чомусь при спробі додати Ukrainian розкладку, Ukrainian Unicode відображається двічи у списку.
<img width="520" alt="screen shot 2018-10-10 at 10 42 02 pm" src="https://user-images.githubusercontent.com/8195501/46777581-f381aa00-ccdd-11e8-9bc6-e836c703000b.png">

**Comment by Nikaaner** [comment]
> Чомусь при спробі додати Ukrainian розкладку, Ukrainian Unicode відображається двічи у списку.

У мене також так було, ось: https://github.com/korzhyk/OSX-Ukrainian-Unicode-Layout/issues/3#issue-271466091

**Comment by valsoray17** [comment]
Після апдейту до Мохаве, проблема зникла.
