### ISSUE TITLE
Додати інсталятор до brew репозиторію

### ISSUE THREAD

**Issue by kopach** [korzhyk/OSX-Ukrainian-Unicode-Layout#9]
Користуюсь даною розкладкою вже досить давно. Але при за кожним разом при зміні комп'ютера - мушу встановлювати її вручну, що досить незручно. Пропоную додати інсталятор до репозиторію [homebrew](https://brew.sh/) щоб можна було завтоматизувати встановлення даної розкладки автоматично за допомогою скриптів. Дякую.
Для довідки, [ось подібна розкладка](https://github.com/denysdovhan/ukrainian-typographic-keyboard/), що дає можливість встановлення через homebrew

**Comment by korzhyk** [comment]
@kopach виглядає дуже ізі 👌

**Comment by korzhyk** [comment]
https://github.com/Homebrew/homebrew-cask/pull/72029

**Comment by korzhyk** [comment]
Створив pull-request https://github.com/Homebrew/homebrew-cask/pull/72029

**Comment by korzhyk** [comment]
Нажаль, cask не принято, оскільки https://github.com/korzhyk/macOS-Ukrainian-Unicode-Layout 
 має недостатньо ⭐️.

**Comment by kopach** [comment]
Що ж, шкода :( 
> Main project is https://github.com/korzhyk/OSX-Ukrainian-Unicode-Layout but actually layout bundle moved into submodule https://github.com/korzhyk/macOS-Ukrainian-Unicode-Layout

А є шанс перемістити все до даного модулю без під-модулів? https://github.com/korzhyk/OSX-Ukrainian-Unicode-Layout Тоді б все запрацювало, я думаю :)

**Comment by korzhyk** [comment]
@kopach спроба номер 2 https://github.com/Homebrew/homebrew-cask/pull/72305

**Comment by kopach** [comment]
Бачу, що `url "https://github.com/korzhyk/macOS-Ukrainian-Unicode-Layout/archive/#{version}.tar.gz"` все ж до іншого репозиторію, тож, мабуть, знову не пройде :( 
Але новий метод встановлення з Readme.md мене цілком влаштовує: ` brew cask install https://github.com/korzhyk/OSX-Ukrainian-Unicode-Layout/raw/master/ukrainian-unicode-layout.rb`. Більшого мені й не треба, дякую.
Але все ж, рекомендую не покидати цю справу і все ж додати цей проєкт до brew (навіть ціною мерджу  двох репозиторіїв) оскільки пошук через сам brew теж може привести людей на цей проєкт.

**Comment by kopach** [comment]
Круто, бачу, що PR спроба №2 спрацювала 🎉
Так, для довідки, якщо хтось читатиме тут, тепер можна встановлювати розкладку так
`brew cask install ukrainian-unicode-layout`
